"""
髋关节假体类别描述模板
从 prompt_templates.py 中抽离的类别描述
用于 BiomedCoOp PMC-CLIP 训练
"""

HIP_PROSTHESIS_TEMPLATES = {
    "Acetabular Loosening": [
        "X-ray showing radiolucent lines around the acetabular cup indicating loosening.",
        "The radiograph reveals gaps between the acetabular component and the surrounding bone.",
        "Acetabular loosening is visible with progressive radiolucent lines greater than 2mm in width.",
        "The X-ray image shows migration of the acetabular cup from its original position.",
        "Radiolucent zones around the acetabular component suggest aseptic loosening.",
        "The radiograph displays a broken or displaced acetabular component.",
        "Acetabular loosening is indicated by osteolysis around the cup on X-ray.",
        "The image shows a tilted or rotated acetabular cup suggesting loosening.",
        "Progressive radiolucent lines around the acetabular socket indicate component loosening.",
        "The X-ray reveals bone resorption around the acetabular implant.",
        "Acetabular component appears displaced with visible gaps from the bone interface.",
        "The radiograph shows signs of acetabular loosening with radiolucent lines in multiple zones.",
        "Osteolytic changes around the acetabular cup are visible on the X-ray image.",
        "The X-ray displays migration of the acetabular component indicating loosening.",
        "Radiolucent lines greater than 2mm around the acetabular cup suggest loosening.",
        "The image shows a loose acetabular component with visible separation from bone.",
        "Acetabular loosening is evident with progressive radiolucent zones on X-ray.",
        "The radiograph reveals bone loss around the acetabular implant interface.",
        "X-ray showing acetabular component instability with radiolucent lines.",
        "The image displays signs of acetabular loosening with component migration.",
        "Radiolucent lines around the acetabular cup indicate aseptic loosening.",
        "The X-ray shows osteolysis and bone resorption around the acetabular component.",
        "Acetabular loosening is visible with broken or displaced cup components.",
        "The radiograph displays progressive radiolucent lines suggesting acetabular loosening.",
        "X-ray image showing gaps between the acetabular cup and surrounding bone.",
        "The image reveals acetabular component loosening with visible radiolucent zones.",
        "Acetabular loosening is indicated by migration and radiolucent lines on X-ray.",
        "The radiograph shows signs of acetabular component failure with loosening.",
        "X-ray displaying osteolytic changes around the acetabular cup interface.",
        "The image shows acetabular loosening with progressive bone loss around the cup.",
        "Radiolucent lines and component migration suggest acetabular loosening on X-ray.",
        "The radiograph reveals acetabular component instability with visible gaps.",
        "X-ray showing signs of acetabular loosening with radiolucent zones.",
        "The image displays acetabular component displacement indicating loosening.",
        "Acetabular loosening is evident with bone resorption around the cup on X-ray.",
        "The radiograph shows progressive radiolucent lines around the acetabular component.",
        "X-ray image revealing acetabular loosening with osteolytic changes.",
        "The image displays acetabular component migration suggesting loosening.",
        "Acetabular loosening is visible with radiolucent lines greater than 2mm on X-ray.",
        "The radiograph shows gaps between the acetabular cup and bone interface.",
        "X-ray revealing signs of acetabular loosening with component instability.",
        "The image shows osteolysis around the acetabular cup indicating loosening.",
        "Acetabular loosening is indicated by progressive radiolucent zones on X-ray.",
        "The radiograph displays bone loss around the acetabular implant interface.",
        "X-ray showing acetabular component loosening with visible separation from bone.",
        "The image reveals acetabular loosening with radiolucent lines in multiple zones.",
        "Acetabular component appears loose with migration visible on X-ray.",
        "The radiograph shows signs of acetabular loosening with osteolytic changes.",
        "X-ray image displaying acetabular component displacement and radiolucent lines.",
        "The image shows acetabular loosening with progressive bone resorption around the cup."
    ],
    "Dislocation": [
        "X-ray showing the femoral head displaced from the acetabular socket.",
        "The radiograph reveals a complete dislocation with the femoral head outside the acetabulum.",
        "Dislocation is visible with the femoral head positioned superiorly or posteriorly to the socket.",
        "The X-ray image shows the hip joint dislocated with loss of normal articulation.",
        "Femoral head appears completely out of the acetabular cup on the radiograph.",
        "The image displays a dislocated hip with the femoral head displaced from its normal position.",
        "X-ray showing posterior dislocation with the femoral head behind the acetabulum.",
        "The radiograph reveals an anterior dislocation with the femoral head in front of the socket.",
        "Dislocation is evident with the femoral head not seated in the acetabular cup.",
        "The X-ray shows a dislocated hip prosthesis with component separation.",
        "Femoral head is completely displaced from the acetabular socket on X-ray.",
        "The radiograph displays signs of hip dislocation with loss of joint congruity.",
        "X-ray image showing the femoral head outside its normal position in the acetabulum.",
        "The image reveals a dislocated hip with visible separation of joint components.",
        "Dislocation is visible with the femoral head positioned abnormally relative to the acetabulum.",
        "The radiograph shows a complete hip dislocation with component displacement.",
        "X-ray displaying the femoral head dislocated from the acetabular socket.",
        "The image shows a dislocated hip prosthesis with visible component separation.",
        "Dislocation is indicated by the femoral head not articulating with the acetabular cup.",
        "The X-ray reveals a dislocated hip with the femoral head outside the socket.",
        "Femoral head appears displaced from the acetabular cup indicating dislocation.",
        "The radiograph shows signs of hip dislocation with abnormal component positioning.",
        "X-ray image revealing a dislocated hip with loss of normal joint alignment.",
        "The image displays a complete dislocation with the femoral head outside the acetabulum.",
        "Dislocation is evident with the femoral head positioned away from the socket on X-ray.",
        "The radiograph shows a dislocated hip prosthesis with component separation.",
        "X-ray showing the femoral head completely out of the acetabular socket.",
        "The image reveals dislocation with visible displacement of the femoral head.",
        "Dislocation is visible with the femoral head not seated in the acetabular cup.",
        "The radiograph displays a dislocated hip with abnormal joint positioning.",
        "X-ray image showing signs of dislocation with femoral head displacement.",
        "The image shows a dislocated hip with the femoral head outside the acetabulum.",
        "Dislocation is indicated by complete separation of the femoral head from the socket.",
        "The X-ray reveals a dislocated hip prosthesis with visible component displacement.",
        "Femoral head appears dislocated from the acetabular cup on the radiograph.",
        "The radiograph shows a dislocated hip with loss of normal articulation.",
        "X-ray displaying dislocation with the femoral head positioned abnormally.",
        "The image reveals a complete dislocation with component separation visible.",
        "Dislocation is evident with the femoral head not articulating with the acetabulum.",
        "The X-ray shows a dislocated hip with the femoral head outside the socket.",
        "Femoral head is completely displaced indicating dislocation on X-ray.",
        "The radiograph displays signs of hip dislocation with abnormal positioning.",
        "X-ray image showing a dislocated hip with visible component separation.",
        "The image shows dislocation with the femoral head displaced from the acetabular cup.",
        "Dislocation is visible with loss of normal joint congruity on X-ray.",
        "The radiograph reveals a dislocated hip prosthesis with component displacement.",
        "X-ray showing the femoral head dislocated from the acetabular socket.",
        "The image displays a dislocated hip with abnormal joint alignment.",
        "Dislocation is indicated by the femoral head not seated in the acetabulum.",
        "X-ray image of a dislocated hip showing complete loss of joint articulation."
    ],
    "Fracture": [
        "X-ray showing a fracture line through the bone with visible discontinuity.",
        "The radiograph reveals a broken bone with displaced fracture fragments.",
        "Fracture is visible with a clear break in the bone cortex on X-ray.",
        "The X-ray image shows a fracture with angulation and displacement of fragments.",
        "Bone fracture is evident with visible fracture lines and fragment separation.",
        "The radiograph displays a comminuted fracture with multiple bone fragments.",
        "X-ray showing a displaced fracture with fragments out of alignment.",
        "The image reveals a fracture with visible bone discontinuity and displacement.",
        "Fracture is indicated by a break in the bone cortex with fragment separation.",
        "The X-ray shows a fracture line with angulation and displacement.",
        "Bone appears fractured with visible discontinuity on the radiograph.",
        "The radiograph displays signs of fracture with broken bone fragments.",
        "X-ray image showing a fracture with displacement and angulation.",
        "The image reveals a bone fracture with visible fracture lines.",
        "Fracture is evident with clear bone discontinuity on X-ray.",
        "The radiograph shows a broken bone with displaced fragments.",
        "X-ray displaying a fracture line through the bone cortex.",
        "The image shows a fracture with visible bone fragment separation.",
        "Fracture is visible with a break in the bone continuity on X-ray.",
        "The radiograph reveals a fracture with angulation and displacement.",
        "X-ray showing signs of fracture with bone discontinuity.",
        "The image displays a fractured bone with visible fracture lines.",
        "Fracture is indicated by a clear break in the bone on X-ray.",
        "The radiograph shows a fracture with fragment displacement.",
        "X-ray image revealing a bone fracture with visible discontinuity.",
        "The image shows a fracture with broken bone fragments visible.",
        "Fracture is evident with a fracture line through the bone cortex.",
        "The radiograph displays a displaced fracture with fragment separation.",
        "X-ray showing a fracture with angulation and bone discontinuity.",
        "The image reveals signs of fracture with visible fracture lines.",
        "Fracture is visible with a break in the bone continuity.",
        "The X-ray shows a fractured bone with displaced fragments.",
        "Bone appears broken with visible fracture lines on the radiograph.",
        "The radiograph shows a fracture with clear bone discontinuity.",
        "X-ray image displaying a fracture with fragment displacement.",
        "The image shows a bone fracture with visible fracture lines.",
        "Fracture is indicated by a break in the bone cortex on X-ray.",
        "The radiograph reveals a fracture with angulation and separation.",
        "X-ray showing a displaced fracture with fragments out of alignment.",
        "The image displays signs of fracture with bone discontinuity.",
        "Fracture is evident with visible fracture lines and fragment separation.",
        "The radiograph shows a broken bone with displaced fragments visible.",
        "X-ray image revealing a fracture with clear bone discontinuity.",
        "The image shows a fracture line through the bone cortex.",
        "Fracture is visible with fragment displacement on X-ray.",
        "The radiograph displays a fracture with visible bone break.",
        "X-ray showing a fractured bone with angulation and displacement.",
        "The image reveals a fracture with fragment separation visible.",
        "Fracture is indicated by bone discontinuity and fragment displacement.",
        "X-ray image of a bone fracture showing clear discontinuity and fragment displacement."
    ],
    "Good Place": [
        "X-ray showing a well-positioned hip prosthesis with proper alignment.",
        "The radiograph reveals a correctly placed acetabular cup and femoral stem.",
        "Good placement is visible with the femoral head properly seated in the acetabulum.",
        "The X-ray image shows optimal component positioning with no signs of malposition.",
        "Hip prosthesis appears well-positioned with proper joint alignment on X-ray.",
        "The radiograph displays a correctly placed implant with good component positioning.",
        "X-ray showing a well-aligned hip prosthesis with proper cup and stem position.",
        "The image reveals optimal placement with the femoral head in the acetabular socket.",
        "Good placement is evident with proper component alignment and positioning.",
        "The X-ray shows a well-positioned hip implant with correct alignment.",
        "Components appear properly positioned with good alignment on the radiograph.",
        "The radiograph shows optimal placement with no signs of malposition.",
        "X-ray image displaying a well-positioned hip prosthesis with proper alignment.",
        "The image reveals good placement with components in correct positions.",
        "Good placement is visible with the femoral head seated in the acetabulum.",
        "The radiograph displays a well-aligned hip prosthesis with proper positioning.",
        "X-ray showing optimal component placement with good alignment.",
        "The image shows a correctly positioned hip implant with proper alignment.",
        "Good placement is indicated by proper component positioning on X-ray.",
        "The radiograph reveals a well-positioned hip prosthesis with correct alignment.",
        "X-ray displaying good placement with the femoral head in the acetabular cup.",
        "The image shows optimal placement with components properly aligned.",
        "Good placement is evident with proper joint alignment on X-ray.",
        "The radiograph shows a well-positioned hip prosthesis with no malposition.",
        "X-ray image revealing good placement with proper component positioning.",
        "The image displays a correctly placed hip implant with good alignment.",
        "Good placement is visible with optimal component positioning on X-ray.",
        "The radiograph shows a well-aligned hip prosthesis with proper placement.",
        "X-ray showing good placement with the femoral head in the acetabulum.",
        "The image reveals optimal placement with components in correct positions.",
        "Good placement is indicated by proper alignment and positioning on X-ray.",
        "The radiograph displays a well-positioned hip prosthesis with correct alignment.",
        "X-ray showing optimal component placement with good positioning.",
        "The image shows a well-positioned hip implant with proper alignment.",
        "Good placement is evident with the femoral head seated in the socket.",
        "The radiograph reveals good placement with proper component positioning.",
        "X-ray image displaying a correctly placed hip prosthesis with alignment.",
        "The image shows optimal placement with components properly positioned.",
        "Good placement is visible with proper joint alignment on X-ray.",
        "The radiograph displays a well-positioned hip prosthesis with good alignment.",
        "X-ray showing good placement with the femoral head in the acetabular cup.",
        "The image reveals optimal component placement with proper positioning.",
        "Good placement is indicated by correct component alignment on X-ray.",
        "The radiograph shows a well-aligned hip prosthesis with optimal placement.",
        "X-ray image revealing good placement with proper component positioning.",
        "The image displays a well-positioned hip implant with correct alignment.",
        "Good placement is evident with optimal component positioning on X-ray.",
        "The radiograph shows a correctly placed hip prosthesis with good alignment.",
        "X-ray showing optimal placement with the femoral head in the acetabulum.",
        "Radiograph of a well-positioned hip prosthesis showing optimal component alignment."
    ],
    "Infection": [
        "X-ray showing signs of periprosthetic infection with bone resorption.",
        "The radiograph reveals osteolytic changes suggesting infection around the implant.",
        "Infection is visible with progressive bone loss and radiolucent zones on X-ray.",
        "The X-ray image shows signs of periprosthetic infection with bone destruction.",
        "Osteomyelitis is evident with bone resorption and periosteal reaction on X-ray.",
        "The radiograph displays signs of infection with progressive bone loss around the implant.",
        "X-ray showing periprosthetic infection with visible bone destruction and resorption.",
        "The image reveals signs of infection with osteolytic changes around the prosthesis.",
        "Infection is indicated by progressive bone loss and radiolucent zones on X-ray.",
        "The radiograph shows periprosthetic infection with bone resorption visible.",
        "X-ray displaying signs of infection with osteolytic changes around the implant.",
        "The image shows periprosthetic infection with progressive bone destruction.",
        "Infection is evident with bone resorption and radiolucent zones on X-ray.",
        "The radiograph reveals signs of infection with visible bone loss around the prosthesis.",
        "X-ray image showing periprosthetic infection with osteolytic changes.",
        "The image displays signs of infection with progressive bone resorption.",
        "Infection is visible with bone destruction around the implant on X-ray.",
        "The radiograph shows periprosthetic infection with radiolucent zones.",
        "X-ray revealing signs of infection with bone loss and destruction.",
        "The image shows periprosthetic infection with osteolytic changes visible.",
        "Infection is indicated by progressive bone resorption on X-ray.",
        "The radiograph displays signs of infection with bone destruction around the implant.",
        "X-ray showing periprosthetic infection with visible osteolytic changes.",
        "The image reveals signs of infection with progressive bone loss.",
        "Infection is evident with radiolucent zones around the prosthesis on X-ray.",
        "The radiograph shows periprosthetic infection with bone resorption.",
        "X-ray image displaying signs of infection with osteolytic changes.",
        "The image shows periprosthetic infection with bone destruction visible.",
        "Infection is visible with progressive bone loss around the implant on X-ray.",
        "The radiograph reveals signs of infection with radiolucent zones.",
        "X-ray showing periprosthetic infection with osteolytic changes around the prosthesis.",
        "The image displays signs of infection with visible bone resorption.",
        "Infection is indicated by bone destruction and radiolucent zones on X-ray.",
        "The radiograph shows periprosthetic infection with progressive bone loss.",
        "X-ray image revealing signs of infection with osteolytic changes.",
        "The image shows periprosthetic infection with bone resorption visible.",
        "Infection is evident with progressive bone destruction on X-ray.",
        "The radiograph displays signs of infection with radiolucent zones around the implant.",
        "X-ray showing periprosthetic infection with visible bone loss.",
        "The image reveals signs of infection with osteolytic changes around the prosthesis.",
        "Infection is visible with bone resorption and destruction on X-ray.",
        "The radiograph shows periprosthetic infection with progressive osteolytic changes.",
        "X-ray image displaying signs of infection with bone resorption.",
        "The image shows periprosthetic infection with visible bone destruction.",
        "Infection is indicated by progressive bone loss around the implant on X-ray.",
        "The radiograph reveals signs of infection with radiolucent zones and bone resorption.",
        "X-ray showing periprosthetic infection with osteolytic changes visible.",
        "The image displays signs of infection with progressive bone destruction.",
        "Infection is evident with bone resorption around the prosthesis on X-ray.",
        "Radiograph showing periprosthetic infection with visible bone destruction and osteolysis."
    ],
    "Native Hip": [
        "X-ray showing a native hip joint with no prosthetic components visible.",
        "The radiograph reveals a natural hip joint without any implants.",
        "Native hip is visible with intact femoral head and acetabulum on X-ray.",
        "The X-ray image shows a natural hip joint with no prosthetic components.",
        "Hip appears native with the femoral head articulating with the natural acetabulum.",
        "The radiograph displays a natural hip joint without prosthetic replacement.",
        "X-ray showing a native hip with intact bone structures and no implants.",
        "The image reveals a natural hip joint with the femoral head in the acetabulum.",
        "Native hip is evident with no prosthetic components visible on X-ray.",
        "The X-ray shows a natural hip joint with intact joint structures.",
        "Hip appears native with no signs of prosthetic replacement on the radiograph.",
        "The radiograph shows a natural hip joint without any implants visible.",
        "X-ray image displaying a native hip with intact bone anatomy.",
        "The image reveals a natural hip joint with no prosthetic components.",
        "Native hip is visible with the femoral head in the natural acetabulum.",
        "The radiograph displays a natural hip joint with intact joint structures.",
        "X-ray showing a native hip with no signs of prosthetic replacement.",
        "The image shows a natural hip joint with intact femoral head and acetabulum.",
        "Native hip is indicated by absence of prosthetic components on X-ray.",
        "The radiograph reveals a natural hip joint without implants.",
        "X-ray displaying a native hip with intact bone structures.",
        "The image shows a natural hip joint with no prosthetic replacement visible.",
        "Native hip is evident with intact joint anatomy on X-ray.",
        "The radiograph shows a natural hip joint with no implants.",
        "X-ray image revealing a native hip with intact bone structures.",
        "The image displays a natural hip joint without prosthetic components.",
        "Native hip is visible with the femoral head in the natural socket.",
        "The radiograph shows a natural hip joint with intact joint structures.",
        "X-ray showing a native hip with no signs of prosthetic replacement.",
        "The image reveals a natural hip joint with intact bone anatomy.",
        "Native hip is indicated by absence of implants on X-ray.",
        "The radiograph displays a natural hip joint without prosthetic components.",
        "X-ray showing a native hip with intact femoral head and acetabulum.",
        "The image shows a natural hip joint with no prosthetic replacement.",
        "Native hip is evident with intact joint structures on X-ray.",
        "The radiograph reveals a natural hip joint with no implants visible.",
        "X-ray image displaying a native hip with intact bone anatomy.",
        "The image shows a natural hip joint without prosthetic components.",
        "Native hip is visible with the femoral head in the natural acetabulum.",
        "The radiograph shows a natural hip joint with intact joint structures.",
        "X-ray showing a native hip with no signs of prosthetic replacement.",
        "The image reveals a natural hip joint with intact bone structures.",
        "Native hip is indicated by absence of prosthetic components on X-ray.",
        "The radiograph displays a natural hip joint without implants.",
        "X-ray image revealing a native hip with intact joint anatomy.",
        "The image shows a natural hip joint with no prosthetic replacement visible.",
        "Native hip is evident with intact bone structures on X-ray.",
        "The radiograph shows a natural hip joint with no implants.",
        "X-ray displaying a native hip with intact femoral head and acetabulum.",
        "Radiograph of a native hip showing natural joint structures without prosthetic components."
    ],
    "Spacer": [
        "X-ray showing a temporary spacer in place between bone segments.",
        "The radiograph reveals a spacer component used in staged revision surgery.",
        "Spacer is visible as a temporary implant placed during infection treatment.",
        "The X-ray image shows a spacer positioned in the hip joint space.",
        "Temporary spacer appears in place between the acetabulum and femur on X-ray.",
        "The radiograph displays a spacer component used for maintaining joint space.",
        "X-ray showing a spacer placed during two-stage revision surgery.",
        "The image reveals a temporary spacer component in the hip joint.",
        "Spacer is evident as a provisional implant on X-ray.",
        "The X-ray shows a spacer positioned to maintain joint space.",
        "Spacer component appears in place on the radiograph.",
        "The radiograph shows a temporary spacer used in revision surgery.",
        "X-ray image displaying a spacer positioned between bone segments.",
        "The image reveals a spacer component maintaining joint space.",
        "Spacer is visible as a temporary implant on X-ray.",
        "The radiograph displays a spacer placed during staged revision.",
        "X-ray showing a temporary spacer component in the hip joint.",
        "The image shows a spacer positioned to maintain joint alignment.",
        "Spacer is indicated by a temporary component visible on X-ray.",
        "The radiograph reveals a spacer used in two-stage revision surgery.",
        "X-ray displaying a spacer component placed between bone segments.",
        "The image shows a temporary spacer maintaining joint space.",
        "Spacer is evident as a provisional implant on X-ray.",
        "The radiograph shows a spacer positioned in the hip joint.",
        "X-ray image revealing a spacer component used in revision surgery.",
        "The image displays a temporary spacer placed between bone segments.",
        "Spacer is visible as a provisional component on X-ray.",
        "The radiograph shows a spacer maintaining joint space.",
        "X-ray showing a spacer component positioned during staged revision.",
        "The image reveals a temporary spacer in the hip joint.",
        "Spacer is indicated by a provisional implant visible on X-ray.",
        "The radiograph displays a spacer used in two-stage revision surgery.",
        "X-ray showing a spacer component placed between bone segments.",
        "The image shows a temporary spacer maintaining joint alignment.",
        "Spacer is evident as a provisional component on X-ray.",
        "The radiograph reveals a spacer positioned in the hip joint.",
        "X-ray image displaying a spacer component used in revision surgery.",
        "The image shows a temporary spacer placed between bone segments.",
        "Spacer is visible as a provisional implant maintaining joint space on X-ray.",
        "The radiograph shows a spacer component positioned during staged revision.",
        "X-ray revealing a temporary spacer in the hip joint.",
        "The image displays a spacer used in two-stage revision surgery.",
        "Spacer is indicated by a provisional component visible on X-ray.",
        "The radiograph shows a spacer positioned between bone segments.",
        "X-ray showing a temporary spacer maintaining joint space.",
        "The image reveals a spacer component placed during revision surgery.",
        "Spacer is evident as a provisional implant on X-ray.",
        "The radiograph displays a temporary spacer in the hip joint.",
        "Radiograph showing a temporary spacer maintaining joint space during revision surgery.",
        "X-ray image showing a spacer component used in staged revision."
    ],
    "Stem Loosening": [
        "X-ray showing radiolucent lines around the femoral stem indicating loosening.",
        "The radiograph reveals gaps between the femoral stem and surrounding bone.",
        "Stem loosening is visible with progressive radiolucent lines greater than 2mm in width.",
        "The X-ray image shows migration of the femoral stem from its original position.",
        "Radiolucent zones around the femoral component suggest aseptic stem loosening.",
        "The radiograph displays a broken or displaced femoral stem component.",
        "Stem loosening is indicated by osteolysis around the stem on X-ray.",
        "The image shows a tilted or subsided femoral stem suggesting loosening.",
        "Progressive radiolucent lines around the femoral stem indicate component loosening.",
        "The X-ray reveals bone resorption around the femoral implant.",
        "Femoral stem appears displaced with visible gaps from the bone interface.",
        "The radiograph shows signs of stem loosening with radiolucent lines in multiple zones.",
        "Osteolytic changes around the femoral stem are visible on the X-ray image.",
        "The X-ray displays migration of the femoral component indicating loosening.",
        "Radiolucent lines greater than 2mm around the femoral stem suggest loosening.",
        "The image shows a loose femoral stem with visible separation from bone.",
        "Stem loosening is evident with progressive radiolucent zones on X-ray.",
        "The radiograph reveals bone loss around the femoral implant interface.",
        "X-ray showing femoral stem instability with radiolucent lines.",
        "The image displays signs of stem loosening with component migration.",
        "Radiolucent lines around the femoral stem indicate aseptic loosening.",
        "The X-ray shows osteolysis and bone resorption around the femoral component.",
        "Stem loosening is visible with broken or displaced stem components.",
        "The radiograph displays progressive radiolucent lines suggesting stem loosening.",
        "X-ray image showing gaps between the femoral stem and surrounding bone.",
        "The image reveals femoral component loosening with visible radiolucent zones.",
        "Stem loosening is indicated by migration and radiolucent lines on X-ray.",
        "The radiograph shows signs of femoral component failure with loosening.",
        "X-ray displaying osteolytic changes around the femoral stem interface.",
        "The image shows stem loosening with progressive bone loss around the stem.",
        "Radiolucent lines and component migration suggest stem loosening on X-ray.",
        "The radiograph reveals femoral component instability with visible gaps.",
        "X-ray showing signs of stem loosening with radiolucent zones.",
        "The image displays femoral component displacement indicating loosening.",
        "Stem loosening is evident with bone resorption around the stem on X-ray.",
        "The radiograph shows progressive radiolucent lines around the femoral component.",
        "X-ray image revealing stem loosening with osteolytic changes.",
        "The image displays femoral component migration suggesting loosening.",
        "Stem loosening is visible with radiolucent lines greater than 2mm on X-ray.",
        "The radiograph shows gaps between the femoral stem and bone interface.",
        "X-ray revealing signs of stem loosening with component instability.",
        "The image shows osteolysis around the femoral stem indicating loosening.",
        "Stem loosening is indicated by progressive radiolucent zones on X-ray.",
        "The radiograph displays bone loss around the femoral implant interface.",
        "X-ray showing femoral component loosening with visible separation from bone.",
        "The image reveals stem loosening with radiolucent lines in multiple zones.",
        "Femoral stem appears loose with migration visible on X-ray.",
        "The radiograph shows signs of stem loosening with osteolytic changes.",
        "X-ray image displaying femoral component displacement and radiolucent lines.",
        "The image shows stem loosening with progressive bone resorption around the stem."
    ],
    "Wear": [
        "X-ray showing signs of polyethylene wear with asymmetric joint space narrowing.",
        "The radiograph reveals component wear with visible joint space reduction.",
        "Wear is visible with asymmetric narrowing of the joint space on X-ray.",
        "The X-ray image shows signs of component wear with joint space loss.",
        "Polyethylene wear is evident with asymmetric joint space narrowing on X-ray.",
        "The radiograph displays signs of wear with visible component degradation.",
        "X-ray showing component wear with asymmetric joint space narrowing.",
        "The image reveals signs of wear with progressive joint space loss.",
        "Wear is indicated by asymmetric narrowing of the joint space on X-ray.",
        "The radiograph shows component wear with visible joint space reduction.",
        "X-ray displaying signs of wear with asymmetric joint space narrowing.",
        "The image shows component wear with progressive joint space loss.",
        "Wear is evident with visible component degradation on X-ray.",
        "The radiograph reveals signs of wear with asymmetric joint space narrowing.",
        "X-ray image showing component wear with joint space reduction.",
        "The image displays signs of wear with progressive joint space narrowing.",
        "Wear is visible with asymmetric joint space loss on X-ray.",
        "The radiograph shows component wear with visible degradation.",
        "X-ray revealing signs of wear with asymmetric joint space narrowing.",
        "The image shows component wear with progressive joint space reduction.",
        "Wear is indicated by asymmetric narrowing of the joint space on X-ray.",
        "The radiograph displays signs of wear with visible joint space loss.",
        "X-ray showing component wear with asymmetric joint space narrowing.",
        "The image reveals signs of wear with progressive component degradation.",
        "Wear is evident with joint space reduction on X-ray.",
        "The radiograph shows component wear with asymmetric narrowing.",
        "X-ray image displaying signs of wear with joint space loss.",
        "The image shows component wear with visible joint space reduction.",
        "Wear is visible with progressive joint space narrowing on X-ray.",
        "The radiograph reveals component wear with asymmetric narrowing.",
        "X-ray showing signs of wear with joint space reduction visible.",
        "The image displays component wear with progressive joint space narrowing.",
        "Wear is indicated by asymmetric joint space loss on X-ray.",
        "The radiograph shows signs of wear with visible component degradation.",
        "X-ray image revealing component wear with asymmetric narrowing.",
        "The image shows signs of wear with progressive joint space reduction.",
        "Wear is evident with joint space narrowing on X-ray.",
        "The radiograph displays component wear with visible joint space loss.",
        "X-ray showing signs of wear with asymmetric joint space narrowing.",
        "The image reveals component wear with progressive degradation.",
        "Wear is visible with joint space reduction on X-ray.",
        "The radiograph shows component wear with asymmetric narrowing visible.",
        "X-ray image displaying signs of wear with joint space loss.",
        "The image shows component wear with progressive joint space narrowing.",
        "Wear is indicated by asymmetric joint space reduction on X-ray.",
        "The radiograph reveals signs of wear with visible component degradation.",
        "X-ray showing component wear with asymmetric joint space narrowing.",
        "The image displays signs of wear with progressive joint space loss.",
        "Wear is evident with visible component degradation on X-ray.",
        "Radiograph showing component wear with asymmetric joint space narrowing and degradation."
    ]
}

